#!/bin/bash
rm todo todo.txt temp.txt &> /dev/null #& means all output (error, regular output) bash scripting
g++ todo.cpp -o todo
./todo add "task1"
./todo add "task2"
./todo add "task3"
./todo delete
./todo view